name: Biome CI

on:
  pull_request:
    branches:
      - main
      - "*"

jobs:
  biome:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./test.db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Check if project is building
        run: npm run setup

      - name: Run Biome CI check
        run: npx @biomejs/biome ci
